Implementing prognostics horizon metric for prog_algs.
nasa/prog_algs pull request #152
Opened 2022-03-23 12:49 UTC by lawrence-hwang

PR recreated due to branch renaming. Implementing prognostics horizon metric for prog_algs.

2022-04-07 17:20 UTC, teubert requested changes

2022-04-07 17:20 UTC, teubert commented on tests/test_metrics.py
> +                if abs(toe.mean[key] - value < 0.1):
```suggestion
                if abs(toe.mean[key] - value) < 0.1:
```

2022-04-07 17:20 UTC, teubert commented on tests/test_metrics.py
> +
Other tests we want:
* Where all criteria are met at different times
* Where 2 criteria are met at once
* Where at least one criteria is met at beginning of the prediction

2022-04-07 17:22 UTC, teubert commented on src/prog_algs/metrics/toe_profile_metrics.py
> +
Return none for each event not met

2022-04-11 16:54 UTC, teubert requested changes
A few changes- mostly documentation. It's almost there!

2022-04-11 16:54 UTC, teubert commented on src/prog_algs/metrics/toe_profile_metrics.py
> +    Compute prognostic horizon metric, given by the difference between a time ti, when the predictions meet specified performance criteria, and the time corresponding to the end of life (EoL).
```suggestion
    Compute prognostic horizon metric, defined as the difference between a time ti, when the predictions meet specified performance criteria, and the time corresponding to the true Time of Event (ToE), for each event.
```

2022-04-11 16:54 UTC, teubert commented on src/prog_algs/metrics/toe_profile_metrics.py
> +    PH = EOL - ti
```suggestion
    PH = ToE - ti
```

2022-04-11 16:54 UTC, teubert commented on src/prog_algs/metrics/toe_profile_metrics.py
> +        criteria_eqn (Callable function): A function calculating whether ground truth meets some criteria for corresponding key in ToEPredictionProfile
```suggestion
        criteria_eqn (Callable function): A function (toe: UncertainData, ground_truth: dict[str, float]) -> dict[str, bool] calculating whether a prediction in ToEPredictionProfile meets some criteria. \n
            | Args: 
            |  * toe (UncertainData): A single prediction of Time of Event (ToE)
            |  * ground truth (dict[str, float]): Ground truth passed into prognostics_horizon
            | Returns: Map of event names to boolean representing if the event has been met. 
            |   e.g., {'event1': True, 'event2': False}
```

2022-04-11 16:54 UTC, teubert commented on src/prog_algs/metrics/toe_profile_metrics.py
> +        ground_truth (dict): Dictionary containing ground truth; specified as key, value pairs for event and its value
```suggestion
        ground_truth (dict): Dictionary containing ground truth; specified as key, value pairs for event and its value. E.g, {'event1': 47.3, 'event2': 52.1, 'event3': 46.1}
```

2022-04-11 16:54 UTC, teubert commented on src/prog_algs/metrics/toe_profile_metrics.py
> +            * keys (list[string], optional): list of keys to use. If not provided, all keys are used.
We don't use keys configuration argument. Instead, we just use print. Please replace this with a description of print

2022-04-11 16:54 UTC, teubert commented on src/prog_algs/metrics/toe_profile_metrics.py
> +        dict: Dictionary containing prognostic horizon calculations (value) for each event (key)
```suggestion
        dict: Dictionary containing prognostic horizon calculations (value) for each event (key). e.g., {'event1': 12.3, 'event2': 15.1}
```

2022-04-11 16:54 UTC, teubert commented on src/prog_algs/metrics/toe_profile_metrics.py
> +    ph_result = {k:False for k in ground_truth.keys()} # False means not yet met; will be either a numerical value or None if met
```suggestion
    ph_result = {k:None for k in ground_truth.keys()} # False means not yet met; will be either a numerical value or None if met
```
Why not start with None and change the comparisons below to "is None" or "is not None"

2022-04-11 16:54 UTC, teubert commented on src/prog_algs/metrics/toe_profile_metrics.py
> +    ph_result = {k:False for k in ground_truth.keys()} # False means not yet met; will be either a numerical value or None if met
Then we should be able to remove lines 80-82

2022-04-11 16:54 UTC, teubert commented on src/prog_algs/predictors/toe_prediction_profile.py
> +        Compute prognostic horizon metric, given by the difference between a time ti, when the predictions meet specified performance criteria, and the time corresponding to the end of life (EoL).
Propagate changes from above.

2022-04-11 16:54 UTC, teubert commented on tests/test_metrics.py
>      l = unittest.TestLoader()
Make sure you add to the playback example as well

2022-04-15 20:25 UTC, lawrence-hwang commented
<img width="264" alt="Screen Shot 2022-04-15 at 1 25 23 PM" src="https://user-images.githubusercontent.com/50124505/163628835-8d9e9cbc-b0d8-4690-b031-6d69600d0bba.png">

2022-04-15 22:23 UTC, lawrence-hwang commented
example: Given a t_p of 100, a ground truth of 500, and predictions of type unweighted samples of 445, 470, 495, 520, and 545, if the beta is 0.6 (i.e., 60% must be within alpha bounds), an alpha of 0.1 would be met. Because true TtE is 400, and 60% is within 40 (i.e. 0.1 * 400), but an alpha of 0.05 would not be met, because only 40% is within 20 of 500

2022-04-26 17:35 UTC, teubert approved these changes

2022-04-27 22:15 UTC, merged