Implementing describe for UncertainData
nasa/prog_algs pull request #153
Opened 2022-03-28 21:17 UTC by lawrence-hwang

Similar to Panda's describe feature, allows user to print statistical information about an UncertainData object.

2022-03-28 23:28 UTC, lawrence-hwang commented
Conducted review of available libraries: prettytable found to be most user friendly

https://stackoverflow.com/questions/9535954/printing-lists-as-tabular-data
https://pypi.org/project/prettytable/

2022-04-13 18:21 UTC, teubert requested changes

2022-04-13 18:21 UTC, teubert commented on src/prog_algs/uncertain_data/uncertain_data.py
> +            print_bool : bool = True
```suggestion
            print : bool = True 
```

2022-04-13 18:21 UTC, teubert commented on src/prog_algs/uncertain_data/uncertain_data.py
> +    def describe(self, title : str, print : bool = True) -> list:
Can we make title an optional argument?

2022-04-13 18:28 UTC, teubert approved these changes

2022-04-13 18:33 UTC, merged