Implementing relative accuracy for UncertainData
nasa/prog_algs pull request #168
Opened 2022-04-27 06:32 UTC by lawrence-hwang

2022-04-27 22:27 UTC, lawrence-hwang commented
suggestion from Chris:
return {key: 1 - (abs(ground_truth[k] - v)/ground_truth[k]) for k,v in self.mean}

2022-04-28 22:06 UTC, teubert requested changes

2022-04-28 22:06 UTC, teubert commented on src/prog_algs/uncertain_data/uncertain_data.py
> +            raise TypeError("Ground truth must be passed as a dictionary argument.")
Ground truth could also be a *.container. We should probably check that out too. Maybe we should make UserDict a base for *.container, or manually check for it.

2022-04-28 22:06 UTC, teubert commented on tests/test_uncertain_data.py
> +from typing import Type
```suggestion
```
Is this needed?

2022-04-29 21:55 UTC, lawrence-hwang commented on src/prog_algs/uncertain_data/uncertain_data.py
> +        Where r is ground truth RUL and p is predicted RUL distribution
r is ground truth
p is predicted mean distribution

2022-04-29 21:56 UTC, lawrence-hwang commented on src/prog_algs/uncertain_data/uncertain_data.py
> +        Prognostics (Goebel et al, 239)
use full name of book. Prognostics: The Science of Making Predictions

2022-04-29 22:44 UTC, teubert commented on src/prog_algs/uncertain_data/uncertain_data.py
> +        if (not isinstance(ground_truth, dict)) and (not isinstance(ground_truth, DictLikeMatrixWrapper)):
```suggestion
        if not (isinstance(ground_truth, dict) or isinstance(ground_truth, DictLikeMatrixWrapper)):
```

2022-04-29 22:50 UTC, teubert approved these changes

2022-04-29 22:52 UTC, merged